### PR TITLE
Enforce Youtube parental control in multi user

### PR DESCRIPTION
**Pull request by skarbat**
* when starting youtube browser, and if parental control is high,
   ensure that the parental control cookie file is up-to-date by copying it.
 * this allows to have parental control setting system wide, even when
   users are created afterwards.

cc @alex5imon

### CODE REVIEW

**Comment by alex5imon** [comment]
@skarbat we will be copying the cookies every time you launch YT that's a big overkill, I don't think it's needed
cc @pazdera @rluz

**Comment by skarbat** [comment]
I thought about that, but found that this cookie is just 1 small file, alternative suggestions on how to auto-apply YT parental without having to go through settings?

**Comment by alex5imon** [comment]
@skarbat maybe it could be part of the process of creating the new user?

**Comment by alex5imon** [comment]
@skarbat I'll close this PR if that's okay

**Comment by skarbat** [comment]
yes, that's perfect - thanks

**Pull request closed without merging**
