### PR TITLE
Rekonq yt browser

### PR DESCRIPTION
**Pull request by skarbat**
These changes add the rekonq browser build, from source, as part of kano-video package.

### CODE REVIEW

**Comment by skarbat** [comment]
cc @alex5imon @rluz

**Comment by alex5imon** [comment]
@skarbat do you want to keep this PR unmerged just in case?

**Comment by skarbat** [comment]
That's right @alex5imon , doesn't hurt for a few days until we can rock&roll with the alternative solution

**Comment by skarbat** [comment]
We discarded this option long ago. Removing this PR @alex5imon @rluz

**Pull request closed without merging**
