### PR TITLE
The path to the bariol font has changed

### PR DESCRIPTION
**Pull request by pazdera**
And it was breaking kano-video.

### CODE REVIEW

**Comment by pazdera** [comment]
I was panicking a bit, but it turned out to be a rather quick fix.

cc @tombettany @alex5imon

**Comment by pazdera** [comment]
Bumped the version of fonts here: https://github.com/KanoComputing/kano-fonts/commit/6320e60c9a976a30f133ff73f298193f0b466bed

**Comment by pazdera** [comment]
Merging so we can put it on today's testing image, but ping me if you see something wrong.

**Comment by tombettany** [comment]
Good spot @pazdera, sorry I moved that and didn't realise that there would be repercussions :s

**Pull request merged**
