### PR TITLE
Fixes vide play problems with playing videos on the RaspberryPI 2

### PR DESCRIPTION
**Pull request by skarbat**
* Fixes a problem where kano-video-cli was sometimes not returning control
 * Addresses a problem where videos cannot be stopped or paused when run via kano-video

### CODE REVIEW

**Comment by skarbat** [comment]
I have simpified the problem by removing one layer of asynchronism in kano-video main app, since the video needs to play on top of it anyway. Tested on both PI/B and 2 and seems to be working well and faster. Could you guys please have a look at this?

@pazdera @tombettany  @carolineclark @convolu

**Comment by convolu** [comment]
It looks good to me :+1:  
@skarbat Is it pushed to scratch? Would you like me to test it?

**Comment by convolu** [comment]
I pushed it to scratch, and testing it, I think it works. Great job @skarbat :smile:

**Comment by skarbat** [comment]
Thank you for testing this @convolu !

**Pull request merged**
